- src/credentials.ts
- src/index.ts
Modify MetadataAuthService to support any external TokenService as argument. TVM for example.
> Support for any external TokenService (TVM for example)

- src/constants.ts
- src/discovery.ts
- src/driver.ts
Use the same event name in DiscoveryService and in driver.
> fix(DiscoveryService): correctly tell driver that endpoint is removed

- src/index.ts
These types are accessible via public API: `IAuthService` as a parameter for `Driver` constructor, `ITokenService` as a parameter for `MetadataAuthService` constructor.
Without direct exports user have to either import that type from specific file inside package (making file layout of a package part of public API), or, since it's only interfaces, replicate types in user code.
> Export missing types from credentials

- src/discovery.ts
Since in that case round-robin endpoint balancing wouldn't work.
> tune(discovery): write debug log if all endpoints are pessimized

- src/credentials.ts
Before we had to wait `MetadataAuthService.TRIES_INTERVAL` (2 seconds) in the first iteration in the while loop, after successful TokenService initialization.
Now I re-fetch token right after init.
Timings before:
```
durationMs: 2095
durationMs: 2085
durationMs: 2090
```
After:
```
durationMs: 73
durationMs: 58
```
Test code
```js
const {Driver, getCredentialsFromEnv, getLogger} = require('ydb-sdk');
const logger = getLogger({level: 'debug'});
const entryPoint = 'grpcs://ydb.serverless.yandexcloud.net:2135';
const dbName = '...';
const authService = getCredentialsFromEnv(entryPoint, dbName, logger);
const driver = new Driver(entryPoint, dbName, authService);
let ctx;
async function run() {
if (!await driver.ready(10000)) {
logger.fatal(`Driver has not become ready in 10 seconds!`); …
```
> Fix MetadataAuthService: refetch token right after init

- package.json
- proto/bundle.js
By default pbjs compiles proto to root['default'] which may have conflicts with project bundles. For example, root.google.protobuf from ydb-sdk bundle hasn't method BoolValue.
> Specifies ydb-sdk protobuf.roots

- package-lock.json
- package.json
`@types/pino` is visible through public API in logging.d.ts, and `getLogger` expose actual `pino` from this package dependencies.
That means that one would have to install `@types/pino` along with `ydb-sdk` to actually use in with TS, and that types version should match version in `ydb-sdk`, even if pino is never actually used outside of `ydb-sdk`.
> fix: Move @types/pino to prod dependencies

- CHANGELOG.md
- src/driver.ts
- src/scheme.ts
- src/table.ts
- src/utils.ts
Which in turn passes them to tableClient and schemaClient.
> tune(driver): pass gRPC client options to driver

- src/credentials.ts
- src/table.ts
Use '/local' db name if no dbName was passed to AnonymousAuthService
constructor.
> fix(AnonymousAuthMetadata): add db name to metadata

- src/index.ts
- src/table.ts
Now you can receive statistics information, for example, the number
of reading rows, affectedShards and so on.
const data = await session.executeQuery(
'select * from series',
{},
AUTO_TX,
undefined,
undefined,
Ydb.Table.QueryStatsCollection.Mode.STATS_COLLECTION_BASIC
);
const stats_rows_read = (data.queryStats!.queryPhases!['0'].
tableAccess!['0'].reads!.rows as Long).low;
const affectedShards = (data.queryStats!.queryPhases!['0'].
affectedShards as Long).low;
> feat(executeQuery): add collectStats parameter

- package.json
When you import ydb-sdk, you was need import pino-pretty by hand
> fix(package.json): move pino-pretty to dependencies

- .github/workflows/ci.yml
- src/__tests__/graceful-session-close.test.ts
- src/__tests__/graceful-session-close.ts
- src/constants.ts
- src/table.ts
- src/test-utils.ts
- src/utils.ts
The access is provided via `onResponseMetadata` callback passed inside
`ExecuteQuerySettings` object. Also this allows to gracefully close
sessions for which server returned metadata value 'session-close' for
the 'x-ydb-server-hints' key.
> feat: provide access to response metadata in `executeQuery`

- src/version.ts
Since compiled sources moved one level deeper from the location of
package.json, the relative path has to be adjusted.
> fix: correctly access package.json

- examples/basic-example-v1/index.ts
- src/table.ts
Add more properties to TableIndex class from proto file
Adds to TableIndex properties:
- withDataColumns
- withGlobalAsync
- dataColumns
- globalIndex
- globalAsyncIndex
TableIndex doesn't have all possible properties available via GRPC
run `examples/basic-example-v1/index.ts`
#203
> feat: add data columns and sync/async index to TableIndex

- .gitignore
- src/credentials.ts
- src/utils.ts
- tsconfig.json
Update `credentials.ts` and `utils.ts` to create instance of `GrpcSerivce` per token update instead of using one instance per application. This must help with unhandled disconnections #175 #150
After discussion with @asmyasnikov and comparison with [go sdk](https://github.com/ydb-platform/ydb-go-sdk) found out that in nodejs sdk grpc service `IamAuthService` created once per application, while in go sdk it created per token renewal call. @asmyasnikov suggested that the problem is with grpc connection, so it's definetely more reliable to use new connection to renew the token. 
```
git clone git@github.com:zeruk/ydb-nodejs-sdk.git
cd ydb-nodejs-sdk
git checkout fix/service-account-credentials-token-refresh
npm i
cd ../yourAwesomeProject
npm i ../ydb-nodejs-sdk
npm run start #start your app …
```
> refactor(auth): new IAM auth grpc service per token update

- .github/workflows/slo.yml
- slo-workload/.dockerignore
- slo-workload/.editorconfig
- slo-workload/.gitignore
- slo-workload/.prettierrc
- slo-workload/Dockerfile
- slo-workload/jest.config.js
- slo-workload/package-lock.json
- slo-workload/package.json
- slo-workload/src/cleanup.ts
- slo-workload/src/create.ts
- slo-workload/src/index.ts
- slo-workload/src/metricsJob.ts
- slo-workload/src/readJob.ts
- slo-workload/src/testConnection.ts
- slo-workload/src/utils/DataGenerator.ts
- slo-workload/src/utils/Executor.ts
- slo-workload/src/utils/PackGenerator.ts
- slo-workload/src/utils/RateLimiter.ts
- slo-workload/src/utils/StructValue.ts
- slo-workload/src/utils/createDriver.ts
- slo-workload/src/utils/defaults.ts
- slo-workload/src/utils/getMaxId.ts
- slo-workload/src/writeJob.ts
- slo-workload/tests/unit/RateLimiter.spec.ts
- slo-workload/tsconfig.json
This PR adds SLO tests. Added [slo-workload app](slo-workload/package.json) as well as [SLO workflow](ydb-platform/slo-tests/.github/workflows/slo.yml@main), using this repo: ydb-platform/slo-tests
Build related changes
It enables SLO workflow in CI and adds SLO-workload, app that uses YDB while it is falling down different ways.
That test proves that SDK is stable against database errors
Test must be successfull (or not, if test success conditions aren't met), there should be grafana dashboard of test
> Ci: Add slo tests

- src/query/query-session-execute.ts
Add support for the pool_id parameter #423.
About pool_id - https://ydb.tech/docs/ru/dev/resource-consumption-management#sozdanie-pula-resursov
Adds the ability to specify pool_id in the query parameters from the query service
For https://ydb.tech/docs/ru/dev/resource-consumption-management#sozdanie-pula-resursov
```js
await driver.queryClient.do({
fn: async (session) => {
await session.execute({
text: `SELECT 1;`,
poolId: 'my-pool-id'
});
},
});
```
#423
> Add support for the pool_id parameter

- package-lock.json
- package.json
- src/topic/internal/internal-topic-client.ts
- src/topic/topic-client.ts
- src/topic/topic-writer.ts
This pull request includes several updates to dependencies and refactors some code to improve functionality and maintainability. The most important changes include updating dependencies in `package.json`, replacing the `uuid` package with the native `crypto` module for generating UUIDs, and making type adjustments in `topic-writer.ts`.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L37-L45): Updated multiple dependencies to their latest versions, including `@grpc/grpc-js`, `jsonwebtoken`, `long`, `luxon`, and `typescript`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L37-L45) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L54-R63)
* …
> Update Long type usage and improve UUID generation in topic client

- package-lock.json
- package.json
- src/table/table-session.ts
This pull request includes changes to the `package.json` file and enhancements to the `TableIndex` class in `src/table/table-session.ts`. The most important changes are:
Enhancements to `TableIndex` class:
* Added a new property `globalUniqueIndex` to the `TableIndex` class.
* Introduced a new method `withGlobalUnique` in the `TableIndex` class to set the `globalUniqueIndex` and reset other index properties.
Changes in `package.json`:
* Modified the repository URL to use the `git+https` protocol.
```ts
let index = new TableIndex("index1").withDataColumns("col1", "col2").withGlobalUnique()
```
> Feat add support for unique index

- src/credentials/static-credentials-auth-service.ts
- src/driver.ts
This PR fixes an issue with database connection initialization in the `Driver` class.
- Removed the `@ensureContext(true)` decorator from the `login` method, which was breaking the request object and preventing authentication in YDB.
- Replaced `origin` with `host` in the `Driver` class constructor, as `origin` returned `null`, causing connection failures.
Without this fix:
- Authentication in YDB fails because the request object is broken.
- Database connection does not establish because `origin` is `null`.
This change ensures that authentication and connection work correctly.
1. Start the application with the updated code.
2. Attempt to authenticate and connect to YDB.
3. Verify that the connection initializes without errors. …
> FIX: Remove the context decorator in StaticCredentialsGrpcService

- packages/value/src/index.ts
- packages/value/src/primitive.ts
На данный момент, при извлечении поля с типом `Uuid` возникает следующая ошибка:
```
backend\node_modules\@ydbjs\retry\dist\cjs\index.js:92
if (error instanceof error_1.CommitError) {
^
TypeError: Right-hand side of 'instanceof' is not an object
at Object.isRetryableError [as retry] (backend\node_modules\@ydbjs\retry\dist\cjs\index.js:92:15)
at retry (backend\node_modules\@ydbjs\retry\dist\cjs\index.js:50:69)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async RefreshTokenRepository.list (backend\src\services\id\refresh_token\refresh_token.repository.ts:18:20)
Emitted 'error' event on Query instance at:
at backend\node_modules\@ydbjs\query\dist\cjs\query.js:345:18
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async …
```
> fix: Получение UUID
