ydb-platform/ydb-js-sdk

package-lock.json
package.json

https://github.com/pinojs/pino/releases/tag/v6.0.0

Update pino to v6 to support formatters

---

src/table.ts

SessionPool periodically calls session.keepAlive() and doesn't handle any errors (eg, BadSession). Rejected session.keepAlive() produces UnhandledPromiseRejectionWarning.
Example:
```
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 235)
(node:16) UnhandledPromiseRejectionWarning: Error: BadSession: [
{
"message": "Session not found: ydb://session/3?node_id=20257&id=NzdiODYzMGMtNDczZWE4NDItMjA0NGVhMTktNmQzYjQ0ZDA=", …
```

Fix UnhandledPromiseRejectionWarning from SessionPool

---

package-lock.json
package.json
src/credentials.ts

Calling service.getToken() without preceding service.initialize()
makes little sense.

fix(MetadataAuthService): call service.initialize() if there is any

---

src/discovery.ts

Also calculate endpoints to remove using getHost() comparator.

tune(discovery): write trace logs when endpoints are updated

---

src/table.ts

Session shouild be deleted only when broken, in other cases release
it. Refactor `_withSession` to handle session retries instead of
`withSessionRetry`.

fix(SessionPool): do not delete session on every error

---

src/credentials.ts
src/discovery.ts
src/retries.ts
src/utils.ts

Cancel waiting for the request to time out if it completes
successfully.

fix(timeouts): better handling of timed out requests

---

src/table.ts

And retry only on BadSession or SessionBusy, on other errors re-throw
an exception.

tunw(withSessionRetry): increase number of retries to 10

---

src/index.ts
src/types.ts

I need typeMetadataKey to publish package which simplified writing code

tune(export): add two additional export to index.ts

---

src/credentials.ts

feat https://github.com/ydb-platform/ydb-nodejs-sdk/commit/7c517aae5c8f9d069de16fec714e3581dfe8f922

Remove ssl defaults from MetadataAuthService

---

src/table.ts

This allows to not mute errors caused by trying to delete a not existing
table. The default behavior remains the same: if a specific `settings`
object is not provided to `dropTable`, errors caused by deleting a not
existing table are muted.
closes #141

fix: add `muteNonExistingTableErrors` to `DropTableSettings` class

---

fixup.sh
jest.config.js
package.json
tsconfig-base.json
tsconfig-cjs.json
tsconfig-esm.json

feat: add esnext target to support using library via ES modules

---

fixup.sh
package.json
tsconfig-base.json

Remove packages from build due to npm using `files` path in any `package.json` it sees.

fix(build): Bugfix npm package

---

.github/ISSUE_TEMPLATE/01_BUG_REPORT.md
.github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/03_CODEBASE_IMPROVEMENT.md
.github/PULL_REQUEST_TEMPLATE.md

Add github templates for pull request, bug report, feature request and codebase improvement

chore(github): add github templates

---

package-lock.json
package.json

Remove persqueue from ydb-sdk-proto, update ydb protos to latest

feat: update ydb-sdk-proto to 1.1.0

---

.github/workflows/ci.yml

update github actions to latest versions: actions/checkout and actions/setup-node

chore(ci): update ci workflow to remove warnings

---

.github/workflows/pr-release.yml

ci: add PR release workflow to test PRs packages

---

slo-workload/README.md

docs: add SLO workload readme

---

src/errors.ts

feat: add error code number

---

src/__tests__/types.test.ts
src/types.ts

Add Variant and Enum types parsing
Feature

Feat/add Enum and Variant types parsing

---

.github/workflows/slo.yml

Update inputs for slo workflow after slo-tests update
SLO test is broken now
https://github.com/ydb-platform/slo-tests/pull/26

feat: add language_id support for slo workflow

---

slo-workload/Dockerfile

ci: update dockerfile entypoint

---

src/__tests__/create-table.test.ts
src/table.ts

Adds all available createTable settings

Feat/add createTable settings

---

slo-workload/package.json

ci(slo): add yandex-cloud/nodejs-sdk for metadata auth

---

src/__tests__/retries.test.ts
src/__tests__/unit/AuthErrors.test.ts
src/__tests__/unit/BackoffSettings.test.ts
src/credentials.ts
src/errors.ts
src/retries.ts
src/utils.ts

Add retries to authServices, add tests for retries and auth errors

---

package-lock.json
package.json

Remove obsolete functionality
Closes #287

Remove "npm run release"

---

examples/transaction-control/README.md
examples/transaction-control/online-read-only.ts
examples/transaction-control/serializable.ts
examples/transaction-control/snapshot-read-only.ts
examples/transaction-control/stale-read-only.ts

docs: add examples for the article

---

src/__tests__/e2e/connection.test.ts

Change `connection.test.ts` to properly test GRPCS connection establishing
2 test cases tests same behaviour for grpc conenction.

chore: fix new connection unit test, to properly test grpcs connections

---

.env.dev.sample
.github/workflows/ci.yml
.gitignore
package-lock.json
package.json
src/__tests__/e2e/connection.test.ts
src/__tests__/e2e/query-service/method-execute.ts
src/__tests__/e2e/query-service/query-service-client.ts
src/__tests__/e2e/query-service/rows-conversion.ts
src/__tests__/e2e/query-service/transactions.ts
src/__tests__/e2e/retries.test.ts
src/__tests__/e2e/table-service/alter-table.test.ts
src/__tests__/e2e/table-service/bulk-upsert.test.ts
src/__tests__/e2e/table-service/bytestring-identity.test.ts
src/__tests__/e2e/table-service/create-table.test.ts
src/__tests__/e2e/table-service/graceful-session-close.test.ts
src/__tests__/e2e/table-service/read-table.test.ts
src/__tests__/e2e/table-service/scan-query.test.ts
src/__tests__/e2e/table-service/types.test.ts
src/__tests__/e2e/topic-service/internal.test.ts
src/__tests__/e2e/topic-service/send-messages.test.ts
src/discovery/endpoint.ts
src/utils/test/init-driver.ts

Fix: Repeated unstable error CANCELLED: Call canceled

---

src/credentials/iam-auth-service.ts

Impossible connect to YDB with json key
Closes https://github.com/ydb-platform/ydb-nodejs-sdk/issues/418
Check YDB connection to Yandex Cloud with SA authorized key
https://github.com/ydb-platform/ydb-nodejs-sdk/issues/418

fix: correct get IAM token with authorized key

---

src/driver.ts
src/utils/authenticated-service.ts

This pull request includes changes to the `src/driver.ts` and `src/utils/authenticated-service.ts` files to improve the handling of endpoints and connection strings. The most important changes include modifying the way secure connections are determined and simplifying the removal of protocols from endpoints.
Improvements to endpoint handling:
* [`src/driver.ts`](diffhunk://#diff-bda213326e78e9028995e292a6a51a3fa201bce4a8dd750adad751ee572e4924L72-R79): Changed the logic to determine if a connection is secure by checking the `settings.endpoint` first and then removing the protocol from the `endpoint` string.
Simplification of protocol removal:
* [`src/utils/authenticated-service.ts`](diffhunk://#diff-73b7738aed0d1967761ba471aa5dc0f6 …

FIX: Bring endpoint and connection string to a single view
